spring:
  application:
    name: springboot_rabbitmq_consumer
  rabbitmq:
    host: 139.9.141.175
    virtual-host: /
    username: admin
    password: 123
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
server:
  port: 9099